# Makefile for compiling libshared and main

# # *****************************************************
# # Variables to control Makefile operation

CXX = g++
FLAGS = -std=c++11 -pthread
RM = rm

# ****************************************************
# # Targets needed to bring the executable up to date

main:
	$(CXX) $(FLAGS) main.cpp -o main

clean:
	$(RM) main
