# Makefile for compiling process_handling.cpp

# # *****************************************************
# # Variables to control Makefile operation

CXX = clang++
FLAGS = -Weverything -std=c++11

# ****************************************************
# # Targets needed to bring the executable up to date

main:
	$(CXX) $(FLAGS) process_handling.cpp -o main

clean:
	@rm -f main
