# Makefile for compiling process_handling.cpp

# # *****************************************************
# # Variables to control Makefile operation

CXX = g++
FLAGS = -std=c++11
RM = rm

# ****************************************************
# # Targets needed to bring the executable up to date

main:
	$(CXX) $(FLAGS) process_handling.cpp -o main

clean:
	$(RM) main
